general:
  # Elastic
  elastichost: "http://databases-elasticsearch-master-hl.default.svc.cluster.local"
  elasticport: 9200
  elasticuser: "elastic"
  elasticindex: "articulos"

  # RabbitMQ
  rabbithost: "monitoring-rabbitmq-headless"
  rabbitport: 5672
  rabbituser: "user"

  # Mariadb
  mariadbname: "my_database"
  mariadbhost: "databases-mariadb-primary"
  mariadbport: 3306
  mariadbuser: "root"

api:
  replicas: 1








  