apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: details-downloader-metrics
  labels:
    app: details
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: details