kind: Service
apiVersion: v1
metadata:
  name: details-downloader-metrics-service
  labels:
    app: details
spec:
  selector:
    app: details
  ports:
  - name: metrics
    port: {{ .Values.detailsDownloader.metrics }}