apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: api-nodeport
      port: 5000
      nodePort: {{ .Values.api.nodePort }}


