apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      name: api-port
      port: 5000
      targetPort: 5000
    - name: metrics
      port: {{.Values.api.metrics}}


