apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: api-port
      port: 5000
    - name: metrics
      port: {{ .Values.api.metrics }}


