apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loader-processor-metrics
  labels:
    app: loader
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: loader