apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus
    version: "8.1.7"
    repository: https://charts.bitnami.com/bitnami
    condition: enablePrometheus

  - name: grafana
    version: "8.2.8"
    repository: https://charts.bitnami.com/bitnami
    condition: enableGrafana
