apiVersion: apps/v1
kind: Deployment
metadata:
  name: jatsxml-processor
  labels:
    app: jatsxml
spec:
  replicas: {{ .Values.jatsxml.replicas }}
  selector:
    matchLabels:
      app: jatsxml
  template:
    metadata:
      labels:
        app: jatsxml
    spec:
      containers:
      - name: jatsxml-processor
        image: deansf/jatsxml-processor
        ports:
          - name: metrics
            containerPort: {{ .Values.jatsxml.metrics }}
        env:
          - name: "ELASTICHOST"
            value: {{ .Values.general.elastichost }}
          - name: "ELASTICPORT"
            value: {{ .Values.general.elasticport | quote }}
          - name: "ELASTICUSER"
            value: {{ .Values.general.elasticuser }}
          - name: "ELASTICINDEX"
            value: {{ .Values.general.elasticindex }}
          - name: "ELASTICPASS"
            valueFrom:
              secretKeyRef:
                name: databases-elasticsearch
                key: elasticsearch-password
                optional: false
          - name: "RABBITHOST"
            value: {{ .Values.general.rabbithost }}
          - name: "RABBITPORT"
            value: {{ .Values.general.rabbitport | quote }}
          - name: "RABBITUSER"
            value: {{ .Values.general.rabbituser }}
          - name: "RABBITPASS"
            valueFrom:
              secretKeyRef:
                name: databases-rabbitmq
                key: rabbitmq-password
                optional: false
          - name: "RABBITCONSUMEQUEUE"
            value: {{ .Values.detailsDownloader.queuename }}
          - name: "MARIADBNAME"
            value: {{ .Values.general.mariadbname }}
          - name: "MARIADBHOST"
            value: {{ .Values.general.mariadbhost }}
          - name: "MARIADBPORT"
            value: {{ .Values.general.mariadbport | quote }}
          - name: "MARIADBUSER"
            value: {{ .Values.general.mariadbuser }}
          - name: "MARIADBPASS"
            valueFrom:
              secretKeyRef:
                name: databases-mariadb
                key: mariadb-root-password
                optional: false
          - name: "METRICSPORT"
            value: {{ .Values.jatsxml.metrics | quote }}
          