apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: downloader-metrics
  labels:
    app: downloader
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: downloader