apiVersion: v2
name: databases
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: mariadb
    version: "11.3.0"
    repository: https://charts.bitnami.com/bitnami
    condition: enableMaria

  - name: elasticsearch
    version: "19.3.0"
    repository: https://charts.bitnami.com/bitnami
    condition: enableElastic
  
  - name: rabbitmq
    version: "10.3.5"
    repository: https://charts.bitnami.com/bitnami
    condition: enableRabbit