-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 18:36:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`groups` ;

CREATE TABLE IF NOT EXISTS `mydb`.`groups` (
  `id` INT NOT NULL,
  `jobs_id` INT NOT NULL,
  `id_job` INT NULL,
  `created` DATETIME NULL,
  `end` DATETIME NULL,
  `stage` VARCHAR(45) NULL,
  `grp_numer` INT NULL,
  `status` VARCHAR(45) NULL,
  `offset` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_jobs_idx` (`jobs_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_jobs`
    FOREIGN KEY (`jobs_id`)
    REFERENCES `mydb`.`jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jobs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jobs` (
  `id` INT NOT NULL,
  `created` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `end` DATETIME NULL,
  `loader` VARCHAR(45) NULL,
  `grp_size` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
